final String mockModList =
    """# This file was automatically generated by Mod Organizer.

-ZCP 1.5d
+G.A.M.M.A. Armors repair like WPO
+G.A.M.M.A. Achievements Balance
+G.A.M.M.A. Economy and Craft_separator
+Shaders cumulative pack for GAMMA
+4- Injury Audio Extended - DesmanMetzger
+3- Soundscape Overhaul - Solarint
+2- Main Menu Theme - Deathcard Cabin - Grokitach
+1- Audio_separator
""";

final String mockModPackMakerList = """ Audio				
https://www.moddb.com/addons/start/1	0	 - Mod 1 author name	 Mod 1 Name	https://www.moddb.com/mods/game-name/addons/mod-1-name-1.2
https://www.moddb.com/addons/start/20	Some Silly Directory 1:Some Silly Directory 2:Some Silly Directory 3/foobar	 - Mod 2 Author	 Mod 2 Name	https://www.moddb.com/mods/game-name/addons/mod-2-name-v3
""";

String generateDownloadPage(String mirrorUrl) {
  return '''
<html>
  <head>
  </head>
  <body>
    <p>Some stuff</p>
    <div>Things on page</div>
    <script>
      \$(document).ready(function() { \$(window).load(function() { setTimeout(function() { window.location.href="$mirrorUrl"; }, 5000); });
      var foobar = "some other bs";
    </script>
  </body>
</html>
''';
}
